### ISSUE TITLE
Please add me to the workshop list

### ISSUE THREAD

**Issue by vionta** [xproc/Workshop-2019-06#1]
Hi Norman,

I Couldn't add me to the workshop list. I have no edit buttons available and local commit replied with a permission denied message.  Will check during the pre-conference courses if there are seats available. 

Regards. 
Jorge Sanchez

remote: Permission to xproc/Workshop-2019-06.wiki.git denied to vionta.
fatal: unable to access 'https://github.com/xproc/Workshop-2019-06.wiki.git/': The requested URL returned error: 403

**Comment by xml-project** [comment]
Done!
